import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import testRouter from "./test.js";
import pingRouter from "./ping.js";
import ownerAdvisorRouter from "./owner-advisor.js";
import paymentsRouter from "./payments.js";
import advisorRouter from "./advisor.js";
import emailRouter from "./email.js";
import whatsappRouter from "./whatsapp.js";
import planRouter from "./plan.js";
import revenueReportsRouter from "./revenue-reports.js";
import intelligenceReportsRouter from "./intelligence-reports.js";
import resolutionHubRouter from "./resolution-hub.js";
import { healthScoresRouter } from "./health-scores.js";
import { benchmarksRouter } from "./benchmarks.js";
import { onboardingRouter } from "./onboarding.js";
import { signalsRouter } from "./signals.js";
import profileRouter from "./profile.js";
import crmWhatsappRouter from "./crm-whatsapp.js";
import subscriptionRouter from "./subscription.js";
import voiceRouter from "./voice.js";
import v1Router from "./v1/index.js";
import bookingsRouter from "./bookings.js";
import resourcesRouter from "./resources.js";
import pricingRouter from "./pricing.js";
import calendarRouter from "./calendar.js";
import otaConnectionsRouter from "./ota-connections.js";
import jimmyRouter from "./jimmy.js";
import jimmyAdvancedRouter from "./jimmy-advanced.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(pingRouter);
router.use(testRouter);
router.use(ownerAdvisorRouter);
router.use(paymentsRouter);
router.use(advisorRouter);
router.use(emailRouter);
router.use(whatsappRouter);
router.use(planRouter);
router.use(subscriptionRouter);
router.use(revenueReportsRouter);
router.use(intelligenceReportsRouter);
router.use(resolutionHubRouter);
router.use(voiceRouter);
router.use("/health-scores", healthScoresRouter);
router.use("/benchmarks",    benchmarksRouter);
router.use("/onboarding",    onboardingRouter);
router.use("/signals",       signalsRouter);
router.use(profileRouter);
router.use(crmWhatsappRouter);
router.use(bookingsRouter);
router.use(resourcesRouter);
router.use(pricingRouter);
router.use(calendarRouter);
router.use(otaConnectionsRouter);
router.use("/v1", v1Router);
router.use(jimmyRouter);
router.use(jimmyAdvancedRouter);

export default router;
