// ─────────────────────────────────────────────────────────────────────────────
// Intelligence Reports API — Founder-only
// Revenue Intelligence Engine endpoints for Owner Dashboard
//
// POST /api/intelligence-reports/generate     — trigger report generation
// GET  /api/intelligence-reports              — list all reports
// GET  /api/intelligence-reports/latest       — most recent ready report
// GET  /api/intelligence-reports/:id          — full 10-section report
// POST /api/intelligence-reports/:id/email    — re-email an existing report
// ─────────────────────────────────────────────────────────────────────────────

import { Router, type IRouter, type Request, type Response } from "express";
import { requireAuth } from "../middleware/jwt.js";
import { ok, err } from "../lib/response.js";
import { generateIntelligenceReport } from "../lib/intelligence-report-generator.js";

const router: IRouter = Router();

const FOUNDER_USER_ID = "d089432d-5d6b-416e-bd29-abe913121d99";

function requireFounder(req: Request, res: Response): boolean {
  if (req.user?.sub !== FOUNDER_USER_ID) {
    res.status(403).json(err("FORBIDDEN", "Intelligence reports are restricted to the founder account.", req.trace_id));
    return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/intelligence-reports/generate
// Body: { periodLabel?, periodType?, periodStart?, periodEnd?, sendEmail? }
// Defaults: current month, no email
// ─────────────────────────────────────────────────────────────────────────────
router.post("/intelligence-reports/generate", requireAuth, async (req: Request, res: Response) => {
  if (!requireFounder(req, res)) return;

  if (!process.env["AI_INTEGRATIONS_OPENAI_BASE_URL"]) {
    res.status(503).json(err("SERVICE_UNAVAILABLE", "AI service not configured.", req.trace_id));
    return;
  }

  const body = req.body as {
    periodLabel?:  string;
    periodType?:   "monthly" | "quarterly" | "yearly";
    periodStart?:  string;   // ISO date string
    periodEnd?:    string;
    sendEmail?:    boolean;
  };

  // Default to current month
  const now        = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1, 0, 0, 0, 0);
  const monthEnd   = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);

  const periodType  = body.periodType  ?? "monthly";
  const periodStart = body.periodStart ? new Date(body.periodStart) : monthStart;
  const periodEnd   = body.periodEnd   ? new Date(body.periodEnd)   : monthEnd;
  const periodLabel = body.periodLabel ?? now.toLocaleString("en-US", { month: "long", year: "numeric" });
  const sendEmail   = body.sendEmail   ?? false;

  req.log.info({ periodLabel, periodType, sendEmail }, "Intelligence report generation triggered");

  try {
    const result = await generateIntelligenceReport(
      { periodLabel, periodType, periodStart, periodEnd, generatedBy: "manual", sendEmail },
      req.log,
    );

    res.status(result.status === "ready" ? 201 : 202).json(ok({
      id:      result.id,
      status:  result.status,
      period:  periodLabel,
      emailed: sendEmail && result.status === "ready",
      message: result.status === "ready"
        ? "10-section intelligence report generated by Sherlock."
        : "Report saved — Sherlock generation failed. Check logs.",
    }, req.trace_id));

  } catch (e) {
    req.log.error({ err: e }, "Intelligence report generation endpoint failed");
    res.status(500).json(err("INTERNAL_ERROR", "Report generation failed.", req.trace_id));
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/intelligence-reports/latest  — most recent ready report
// MUST be before /:id
// ─────────────────────────────────────────────────────────────────────────────
router.get("/intelligence-reports/latest", requireAuth, async (req: Request, res: Response) => {
  if (!requireFounder(req, res)) return;

  try {
    const { db, intelligenceReports } = await import("@workspace/db");
    const { desc, eq } = await import("drizzle-orm");

    const [report] = await db.select().from(intelligenceReports)
      .where(eq(intelligenceReports.status, "ready"))
      .orderBy(desc(intelligenceReports.createdAt))
      .limit(1);

    if (!report) {
      res.status(404).json(err("NOT_FOUND", "No intelligence reports generated yet.", req.trace_id));
      return;
    }

    res.json(ok(report, req.trace_id));

  } catch (e) {
    req.log.error({ err: e }, "Intelligence reports latest fetch failed");
    res.status(500).json(err("INTERNAL_ERROR", "Could not fetch latest report.", req.trace_id));
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/intelligence-reports  — list with pagination
// ─────────────────────────────────────────────────────────────────────────────
router.get("/intelligence-reports", requireAuth, async (req: Request, res: Response) => {
  if (!requireFounder(req, res)) return;

  try {
    const { db, intelligenceReports } = await import("@workspace/db");
    const { desc, sql } = await import("drizzle-orm");

    const page     = Math.max(1, parseInt(String(req.query["page"] ?? "1")) || 1);
    const pageSize = Math.min(20, Math.max(1, parseInt(String(req.query["pageSize"] ?? "10")) || 10));

    const [rows, [{ total }]] = await Promise.all([
      db.select({
        id:                intelligenceReports.id,
        periodLabel:       intelligenceReports.periodLabel,
        periodType:        intelligenceReports.periodType,
        periodStart:       intelligenceReports.periodStart,
        periodEnd:         intelligenceReports.periodEnd,
        status:            intelligenceReports.status,
        confidenceScore:   intelligenceReports.confidenceScore,
        dataQualityNote:   intelligenceReports.dataQualityNote,
        generatedBy:       intelligenceReports.generatedBy,
        emailedTo:         intelligenceReports.emailedTo,
        emailedAt:         intelligenceReports.emailedAt,
        s1ExecutiveSummary: intelligenceReports.s1ExecutiveSummary,
        s10NetBusinessImpact: intelligenceReports.s10NetBusinessImpact,
        createdAt:         intelligenceReports.createdAt,
      }).from(intelligenceReports)
        .orderBy(desc(intelligenceReports.createdAt))
        .limit(pageSize).offset((page - 1) * pageSize),

      db.select({ total: sql<number>`count(*)::int` }).from(intelligenceReports),
    ]);

    res.json(ok({
      reports:    rows,
      pagination: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) },
    }, req.trace_id));

  } catch (e) {
    req.log.error({ err: e }, "Intelligence reports list failed");
    res.status(500).json(err("INTERNAL_ERROR", "Could not fetch reports.", req.trace_id));
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/intelligence-reports/:id  — full report with all 10 sections
// ─────────────────────────────────────────────────────────────────────────────
router.get("/intelligence-reports/:id", requireAuth, async (req: Request, res: Response) => {
  if (!requireFounder(req, res)) return;

  const id = parseInt(String(req.params["id"] ?? ""));
  if (isNaN(id)) {
    res.status(400).json(err("VALIDATION_ERROR", "Invalid report ID.", req.trace_id));
    return;
  }

  try {
    const { db, intelligenceReports } = await import("@workspace/db");
    const { eq } = await import("drizzle-orm");

    const [report] = await db.select().from(intelligenceReports).where(eq(intelligenceReports.id, id));
    if (!report) {
      res.status(404).json(err("NOT_FOUND", "Report not found.", req.trace_id));
      return;
    }

    res.json(ok(report, req.trace_id));

  } catch (e) {
    req.log.error({ err: e }, "Intelligence report fetch failed");
    res.status(500).json(err("INTERNAL_ERROR", "Could not fetch report.", req.trace_id));
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/intelligence-reports/:id/email  — re-email an existing report
// ─────────────────────────────────────────────────────────────────────────────
router.post("/intelligence-reports/:id/email", requireAuth, async (req: Request, res: Response) => {
  if (!requireFounder(req, res)) return;

  const id = parseInt(String(req.params["id"] ?? ""));
  if (isNaN(id)) {
    res.status(400).json(err("VALIDATION_ERROR", "Invalid report ID.", req.trace_id));
    return;
  }

  try {
    const { db, intelligenceReports } = await import("@workspace/db");
    const { eq, sql } = await import("drizzle-orm");
    const { sendMail } = await import("../lib/mailer.js");

    const [report] = await db.select().from(intelligenceReports).where(eq(intelligenceReports.id, id));
    if (!report) {
      res.status(404).json(err("NOT_FOUND", "Report not found.", req.trace_id));
      return;
    }
    if (report.status !== "ready") {
      res.status(422).json(err("INVALID_STATE", "Report is not ready — cannot email.", req.trace_id));
      return;
    }

    const summary = report.s1ExecutiveSummary ?? "See full report in your Owner Dashboard.";
    const impact  = (report.s10NetBusinessImpact as Record<string, unknown> | null)?.["verdictOneLiner"] ?? "";

    const emailText = `HostFlow AI — Revenue Intelligence Report | ${report.periodLabel}

${summary}

${impact}

━━━━━━━━━━━━━━━━━━
View the full 10-section report in your Owner Dashboard → Revenue Intelligence.

Confidence Score: ${report.confidenceScore ?? "N/A"}/100
Data Quality: ${report.dataQualityNote ?? ""}

Sherlock | HostFlow AI Revenue Intelligence Engine
Generated: ${report.createdAt.toISOString()}`.trim();

    const result = await sendMail({
      to:       "naumansherwani@hostflowai.net",
      subject:  `HostFlow AI — Revenue Intelligence Report | ${report.periodLabel}`,
      text:     emailText,
      identity: "revenue",
    });

    if (!result.success) {
      res.status(502).json(err("EMAIL_FAILED", result.error ?? "Email delivery failed.", req.trace_id));
      return;
    }

    await db.update(intelligenceReports)
      .set({ emailedTo: "naumansherwani@hostflowai.net", emailedAt: sql`now()`, updatedAt: sql`now()` })
      .where(eq(intelligenceReports.id, id));

    res.json(ok({ emailed: true, messageId: result.messageId, provider: result.provider }, req.trace_id));

  } catch (e) {
    req.log.error({ err: e }, "Intelligence report email failed");
    res.status(500).json(err("INTERNAL_ERROR", "Could not send email.", req.trace_id));
  }
});

export default router;
